version: "3.3"
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      # It would be nice here to support OSes that don't have /tmp
      # See: https://github.com/docker/compose/issues/3344
      - "/tmp/var_lib_postgresql_data:/var/lib/postgresql/data"
  cms_dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8889:8889 # Will be needed to expose web server for admin
      - 8888:8888 # Will be needed to expose web server for contests
      - 8890:8890 # RankingWebServers
      - 29000:29000
      - 28000:28000
      - 28500:28500
      - 22000:22000
      - 25000:25000
      - 26000:26000
      - 26001:26001
      - 26002:26002
      - 21000:21000
      - 21100:21100
      - 28600:28600
      - 25123:25123
      - 27501:27501
    depends_on:
      - "db"
    environment:
      CMS_CONFIG: /usr/local/etc/cms.conf
    privileged: true
    command: bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
# psql -h db -p 5432 -U postgres will be very useful!